name: Javascript action

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Commands
        run: |
          pwd
          ls
          uname
      - name: Simple JS Action
        id: stepgreet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: "Rohit N B"
      - name: Log Output
        run: |
          echo "${{steps.stepgreet.outputs.time}}"
          echo "Does this work? Mr. ${{steps.stepgreet.outputs.nameToGreet}}"
