name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: echo "Hello Rohit, this is from Actions!"
      - name: Something else
        run: |
          node -v
          npm -v
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Bash PWD
        run: pwd
        shell: bash